---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
- name: query
  run_list: [
    "recipe[metrics-repose::default]",
    "recipe[metrics-repose::query]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-ip-user]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-api-validator]"
  ]
  attributes:
    repose:
      query_servers: ["127.0.0.1", "127.0.0.2"]
      query:
        container_port: "9001"
- name: ingest
  run_list: [
    "recipe[metrics-repose::default]",
    "recipe[metrics-repose::ingest]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-ip-user]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-api-validator]"
  ]
  attributes:
    repose:
      ingest_servers: ["127.0.0.3", "127.0.0.4"]
      ingest:
        container_port: "9011"
